In [27]:
'''1. Student Marks Array'''

import numpy as np
marks = np.array([78, 65, 89, 56, 92])
print("Array:", marks)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Array: [78 65 89 56 92]
Shape: (5,)
Size: 5
Data type: int64


In [28]:
'''2. Student Marks Access'''

import numpy as np
marks = np.array([72, 85, 64, 90, 76])
print("Array:", marks)
print("First student:", marks[0])
print("Third student:", marks[2])
print("First three students:", marks[0:3])
print("Last two students:", marks[-2:])

Array: [72 85 64 90 76]
First student: 72
Third student: 64
First three students: [72 85 64]
Last two students: [90 76]


In [29]:
import numpy as np

data = np.array([78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92])
marks_matrix = data.reshape(5, 3)

print("Input Data (Flat):", data)
print("Reshaped Matrix (5 Students x 3 Subjects):\n", marks_matrix)

Input Data (Flat): [78 85 90 65 72 80 88 91 84 56 62 70 95 89 92]
Reshaped Matrix (5 Students x 3 Subjects):
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]


In [30]:
import numpy as np

internal_marks = np.array([15, 18, 12, 19, 14])
external_marks = np.array([65, 70, 55, 75, 60])
final_marks = internal_marks + external_marks

print("Internal Marks:", internal_marks)
print("External Marks:", external_marks)
print("Final Marks:", final_marks)

Internal Marks: [15 18 12 19 14]
External Marks: [65 70 55 75 60]
Final Marks: [80 88 67 94 74]


In [31]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])
passed_mask = marks >= 50
passed_students = marks[passed_mask]

print("All Marks:", marks)
print("Students scoring 50 or above:", passed_students)

All Marks: [45 78 56 32 91]
Students scoring 50 or above: [78 56 91]


In [32]:
import numpy as np

marks_matrix = np.array([    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

average_marks = np.mean(marks_matrix, axis=1)

print("Marks Matrix:\n", marks_matrix)
print("Average Marks of each student:", average_marks)

Marks Matrix:
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Average Marks of each student: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


In [33]:
import numpy as np

marks = np.array([67, 82, 91, 74, 58])

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard Deviation: 11.46472851837321


In [34]:
import numpy as np

marks_matrix = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
subject_totals = np.sum(marks_matrix, axis=0)

print("Marks Matrix:\n", marks_matrix)
print("Total marks obtained in each subject:", subject_totals)

Marks Matrix:
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks obtained in each subject: [382 399 416]


In [35]:
import numpy as np

marks_matrix = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_totals = np.sum(marks_matrix, axis=1)

print("Marks Matrix:\n", marks_matrix)
print("Total marks obtained by each student:", student_totals)

Marks Matrix:
 [[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks obtained by each student: [253 217 263 188 276]


In [36]:
import numpy as np

marks = np.array([245, 278, 219, 290, 256])
sorted_marks = np.sort(marks)[::-1]
student_ranks = np.argsort(marks)[::-1] + 1

print("Original Marks:", marks)
print("Sorted Marks (High to Low):", sorted_marks)
print("Ranking of original students (1st is highest):", student_ranks)

Original Marks: [245 278 219 290 256]
Sorted Marks (High to Low): [290 278 256 245 219]
Ranking of original students (1st is highest): [4 2 5 1 3]


In [37]:
import numpy as np

marks = np.array([85, 92, 85, 76, 92])
unique_marks = np.unique(marks)

print("Original Marks:", marks)
print("Unique Marks:", unique_marks)

Original Marks: [85 92 85 76 92]
Unique Marks: [76 85 92]


In [38]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

average_mark = np.nanmean(marks)

print("Marks with missing value:", marks)
print("Average Marks (excluding missing):", average_mark)

Marks with missing value: [78. 85. nan 92. 67.]
Average Marks (excluding missing): 80.5


In [39]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])
average_mark = np.nanmean(marks)

print("Marks with missing value:", marks)
print("Average Marks (excluding missing):", average_mark)

Marks with missing value: [78. 85. nan 92. 67.]
Average Marks (excluding missing): 80.5


In [40]:
import numpy as np

marks = np.array([95, 82, 74, 61, 45])

grades = np.select(
    [marks >= 90, marks >= 80, marks >= 70, marks >= 60],
    ["A", "B", "C", "D"],
    default="F"
)

print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


In [41]:
import numpy as np

marks = np.random.randint(0, 101, 5)

print("Random Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Random Marks: [91 83 35 78 79]
Total: 366
Average: 73.2
Highest: 91
Lowest: 35


In [42]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
highest = np.max(marks, axis=1)
lowest = np.min(marks, axis=1)

class_average = np.mean(total)

print("Marks:")
print(marks)

print("Total:", total)
print("Average:", average)
print("Highest:", highest)
print("Lowest:", lowest)
print("Class Average:", class_average)

print("Students above class average:")

for i in range(5):
    if total[i] > class_average:
        print("Student", i + 1)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total: [253 217 263 188 276]
Average: [84.33333333 72.33333333 87.66666667 62.66666667 92.        ]
Highest: [90 80 91 70 95]
Lowest: [78 65 84 56 89]
Class Average: 239.4
Students above class average:
Student 1
Student 3
Student 5
